CREATE TABLE IF NOT EXISTS users (
    id TEXT NOT NULL PRIMARY KEY,
    email TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users_winks (
  id TEXT NOT NULL PRIMARY KEY,
  user_id TEXT NOT NULL,
  wink_id TEXT NOT NULL
);
